added db and kafka writer/reader
dexguitar/chatapp pull request #4
Opened 2024-04-02 15:10 UTC by dexguitar

2024-04-04 12:36 UTC, snaffi requested changes

2024-04-04 12:36 UTC, snaffi commented on cmd/server.go
> +			fmt.Println(err)
если ошибка то выйди из функции. Твоя программа не может запуститься и корректно проиницилизироваться если не может подключиться к бд

2024-04-04 12:36 UTC, snaffi commented on cmd/server.go
> +		h := utils.InitializeHandler(database.GetDB())
это ведь через wire должно проходить. А почему кстати это utils?

2024-04-04 12:36 UTC, snaffi commented on cmd/server.go
> +			fmt.Printf("error occured while shutting down server: %s", err.Error())
делай return

верхнеуровневый обработчик твоей команды должен логировать это. Еще надо испольовать логи а не принты

для логирования используй slog из stdlib

2024-04-04 12:36 UTC, snaffi commented on db/db.go
>  }
а зачем делаешь обертку над бд?

2024-04-04 12:36 UTC, snaffi commented on internal/handler/user.go
> +	}
кстати с помощью generic'ов можешь сделать оберточку которая позволит строготипизировать твои хэндлеры по сути ты сможешь так объявить их

```go
func MyHandler(ctx context.Context, payload model.User) (model.RegisterResponse, error)
```

2024-04-04 12:36 UTC, snaffi commented on internal/handler/user.go
> +	user := &model.User{}
если придерживаться чистой архитектуры то модели не могут использоваться для описания тела запроса и тела ответа потому что в моделях лежат сущности для работы с бизнес логикой а не для коммуникации по HTTP

2024-04-04 12:36 UTC, snaffi commented on internal/handler/user.go
> +	err = h.Service.RegisterUser(h.Context, user)
ты должен передать контекст полученный из request.Context, а не из структуры. 

В структуре нет смысла хранить контекст. Твоя задача передать контекст из request потому что только этот контекст содержит информацию о запросе. То есть если клиент отключится от твоего сервера то отменится контекст внутри request а не тот который в структуре Handler

2024-04-04 12:36 UTC, snaffi commented on internal/handler/user.go
> +		http.Error(writer, fmt.Sprintf("error registering user: %s", err.Error()), http.StatusInternalServerError)
если ты в ответе сервера будешь записывать ошибки то ты можешь выдать информацию о твой инфратруктуре например какую бд используешь и по какому адресу она находится ;-)

например не смог подключиться к бд то в ошибке будет содержаться айпи адрес куда стучался а еще может быть и логин с паролем ;-)

2024-04-04 12:36 UTC, snaffi commented on cmd/server.go
> +		queue.Producer.ProduceMessages()
не понятно зачем это тут. Ведь продусер это не фоновый процесс. Мы пишем сообщения например из сервисного слоя где определена бизнес логика.

2024-04-04 12:36 UTC, snaffi commented on internal/queue/const.go
> +	topic = "chatapp"
лучше через конфиг задавать

2024-04-04 12:36 UTC, snaffi commented on internal/model/user.go
> +type User struct {
кажется не хватает идентификатора

2024-04-04 18:13 UTC, dexguitar commented on cmd/server.go
> +		h := utils.InitializeHandler(database.GetDB())
> это ведь через wire должно проходить.
Не понял немного... Это же и есть сгенерированная через wire функция, которую я вставил в код.

utils - потому что wire - вспомогательный инструмент. Как надо сделать?

2024-04-04 18:35 UTC, dexguitar commented on cmd/server.go
> +		queue.Producer.ProduceMessages()
Да, забыл пометить - это как тренировочное было, чтоб понять, работает ли вообще.

2024-04-11 15:30 UTC, dexguitar commented on cmd/server.go
> +			fmt.Printf("error occured while shutting down server: %s", err.Error())
Расставил, но не уверен, что правильно

2024-04-17 14:58 UTC, dexguitar commented on internal/handler/user.go
> +	}
А зачем?

2024-04-26 06:14 UTC, snaffi requested changes

2024-04-26 06:14 UTC, snaffi commented on cmd/migrate.go
> +			logger.Error(fmt.Sprintf("could not initialize database connection: %s", err.Error()))
для удобства и чтобы код не захламлялся надо логировать верхнеуровнево

то есть твой код не должен ничего логировать 

логирование происходит скажем так в точке входа. В твоем случае это происходит в 

`root.go`

```go
if err = rootCmd.Execute(); err != nil {
```

2024-04-26 06:14 UTC, snaffi commented on cmd/server.go
> +		h := utils.InitializeHandler(database, logger)
если пользоваться wire то он должен сам создать внутри себя подключение к бд и прочее

давай созвонимся я тебе покажу как это правильнее делать

2024-04-26 06:14 UTC, snaffi commented on cmd/server.go
> +		queue.Consumer.ConsumeMessages()
кажется это должно быть в горутине. Выглядит так что код тут заблокируется и программа не сможет получить сигнал SIGTERM, SIGINT от операционной системы чтобы завершить работу

2024-04-26 06:14 UTC, snaffi commented on configs/defaults.go
> +	defaultConsumerGroup = "test-group"
константы обычно заводятся для переиспользования

раз это значения по умолчанию то достаточно их просто явно прописать в `v.SetDefault`

2024-04-26 06:14 UTC, snaffi commented on internal/handler/user.go
> +	}
чтобы в каждом контроллере вручную не декодировать тело запроса

плюс можешь инкапсулировать логику по валидации тела запроса

например моделька отвечающая за тело запроса может иметь метод Validate() который будет вызываться каждый раз.



по сути все что у тебя происходит с 32 по 45 строчку будет вынесено в отдельную функцию и переиспользовано 

плюс также ты сможешь возвращать ошибки из своих контроллеров и логировать их верхнеуровнево а не вручную каждый раз

плюс сможешь сделать так чтобы контроллеры возвращали объекты которые нужно отдать клиенту  а не вручную сериализовывать в JSON и записывать в ответ

2024-04-26 06:14 UTC, snaffi commented on internal/handler/user.go
> +		http.Error(writer, fmt.Sprintf("error decoding user: %s", err.Error()), http.StatusInternalServerError)
если не удалось декодировать то возвращают статус BadRequest

2024-04-26 06:14 UTC, snaffi commented on internal/queue/consumer.go
> +func (c *KafkaConsumer) ConsumeMessages() {
consume messages должен принимать контекст

2024-04-26 06:14 UTC, snaffi commented on internal/repo/user.go
> +	_, err = conn.ExecContext(ctx, query, user.Username, user.Email, user.Password)
вот допустили ошибочку

если решил использовать метод `Conn` то ты обязаен потом вызвать `conn.Close()` чтобы вернуть соединение в пул 

по этому чтобы такую ошибку больше не совершать ты можешь вызывать методы ExecContext, Query etc напрямую у объекта u.DB

2024-05-13 08:38 UTC, snaffi commented on internal/handler/ws.go
> +		slog.Warn("error %s when upgrading connection to websocket", err)
надо бы ошибочку вернуть пользователю

смотри в го когда происходит ошибка функции обычно возвращают zeroValue в твоем случае conn будет nil

следовательно добавив nil в хаб ты на него напорешься и словишь панику

2024-05-13 08:39 UTC, snaffi commented on .gitignore
> +wire_gen.go
это не должно быть в игноре

оно должно комититься

2024-05-13 08:43 UTC, snaffi commented on cmd/wire.go
> +}
давай использовать chi в качестве роутера, у него классное апи которое позволяет очень удобно создавать мидлвари и прочее 

также создание надо вынести в модуль handler. Так как он должен инкапсулировать эту логику

по сути handler модуль дожен вернуть http.Handler (его реализует http.ServeMux или chi) и все :-)

2024-05-13 08:44 UTC, snaffi commented on internal/handler/handler.go
> +		}
могут быть get запросы и у них нет тела запроса

2024-05-13 08:46 UTC, snaffi commented on internal/handler/ws.go
> +	wsh.Hub.AddConn(username, conn)
вот ты добавил в хаб и потом выходишь из функции что приведет к закрытие соединения

давай **ОТДЕЛЬНЫМ** пул реквестом обработку сокетов сделаем

подумай о том какой жизненный цикл у вебсокет соединения и как будет данные туда отправлять

2024-05-13 08:47 UTC, snaffi commented on internal/repo/user.go
> +func (u *UserRepository) CreateUser(ctx context.Context, user *model.User) error {
лучше объект db передавать в метод

это даст гибкости чтобы на уровне бизнес логики решать что в транзакции а что нет выполнять

2024-05-13 08:48 UTC, snaffi commented on internal/repo/user.go
> +		return &user, err
Не понятен смысл сего действия.



еще почитай как ошибки обрабатывать

https://go.dev/blog/go1.13-errors

2024-05-14 17:00 UTC, dexguitar commented on internal/repo/user.go
> +func (u *UserRepository) CreateUser(ctx context.Context, user *model.User) error {
> это даст гибкости чтобы на уровне бизнес логики решать что в транзакции а что нет выполнять

Не очень понял. Можешь привести пример, когда нам такое поведение необходимо?

2024-06-11 14:12 UTC, snaffi requested changes

2024-06-11 14:12 UTC, snaffi commented on internal/handler/handler.go
> +type TargetFunc[In Validator, Out any] func(context.Context, In) (Out, error)
it's better to call handlerfunc

2024-06-11 14:12 UTC, snaffi commented on internal/handler/handler.go
> +			}
please no. Don't do any dirty hacks.

you can use that library for example

https://github.com/monoculum/formam

2024-06-11 14:12 UTC, snaffi commented on internal/handler/handler.go
> +			}
it duplicated code from above

2024-06-11 14:12 UTC, snaffi commented on internal/handler/handler.go
> +				http.Error(w, "invalid request", http.StatusBadRequest)
why BadRequest?

2024-06-11 14:12 UTC, snaffi commented on internal/handler/handler.go
> +				if errors.Is(err, pgx.ErrNoRows) {
you shouldn't expose DB errors

all db related errors must be handled in repo layer

2024-06-11 14:12 UTC, snaffi commented on internal/handler/router.go
> +	r.Get("/getUserById", Handle(uh.UserService.GetUserById))
please read about how to design rest application

https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design

2024-06-11 14:12 UTC, snaffi commented on internal/model/user.go
> +	Password string `json:"password"`
domain models shouldn't have any kind of struct tags. 

For request/response models you have to create dedicated model in handler package

2024-06-11 14:12 UTC, snaffi commented on internal/repo/user.go
> +	q := "SELECT * FROM users WHERE username = $1 AND password = $2"
you should enumerate columns explicitly because order of columns is not specified.

2024-08-26 06:25 UTC, snaffi commented on internal/handler/handler.go
> +			r.ParseForm()
бери r.URL.Query()

2024-08-26 06:25 UTC, snaffi commented on internal/handler/handler.go
> +			err := decoder.Decode(r.Form, &request.Body)
бери r.URL.Query() вместо r.Form

2024-08-26 06:26 UTC, snaffi commented on internal/handler/handler.go
> +		ctx := context.Background()
r.Context()

2024-08-26 06:28 UTC, snaffi commented on internal/repo/user.go
> +		return nil, utils.NewCustomError("internal server error", http.StatusInternalServerError, fmt.Errorf("%s: %w", op, err))
вынести в отдельную функцию HandleError

2024-08-26 06:30 UTC, snaffi commented on internal/repo/user.go
> +		}
создай собственый тип ошибки

```
var ErrNotFound = errors.New("not found")

2024-08-26 06:31 UTC, snaffi commented on internal/utils/errors.go
> +package utils
переименуй пакет в errors

2024-08-26 06:36 UTC, snaffi commented on internal/repo/user.go
> +	q := "SELECT id, username, email, password FROM users WHERE username = $1"
https://github.com/jackc/pgxutil

2024-08-26 06:38 UTC, snaffi commented on internal/service/contract.go
> +	FindUserById(ctx context.Context, id string, db pg.Read) (*model.User, error)
рекомендую db вторым аргументом передавать

2024-08-26 06:43 UTC, snaffi commented on internal/service/user.go
> +func (u *UserService) RegisterUser(ctx context.Context, req *handler.Request[handler.CreateUserReq]) (*handler.Response[*handler.CreateUserRes], error) {
создай модель CreateUser 

слой сервиса ничего не должен занть об http и прочих контроллерах

2024-08-26 06:44 UTC, snaffi commented on internal/service/user.go
> +	}, nil
сервисный слой ничего не возвращает и не принимает ничего связанного с http


метод должен вернуть User

2024-09-06 09:31 UTC, snaffi commented on internal/errs/errs.go
> +		StatusCode: statusCode,
о статус кода она ничего не должна знать

это решает контроллер

2024-09-06 09:31 UTC, snaffi commented on internal/handler/handler.go
> +			err := decoder.Decode(r.URL.Query(), &request.Body)
в метод гет не передают тело запроса. Только query параметры

2024-09-06 09:32 UTC, snaffi commented on internal/handler/user.go
> +		return nil, errs.NewCustomError(errs.ErrInternal.Error(), http.StatusInternalServerError, fmt.Errorf("%s: %w", op, err))
тут можно просто ошибку вернуть и все. Твой враппер ее просто залогирует.

2024-09-06 09:33 UTC, snaffi commented on internal/repo/user.go
> +		handleError(err, op)
return

2024-09-06 09:33 UTC, snaffi commented on internal/repo/user.go
> +		handleError(err, op)
return

2024-09-07 11:18 UTC, dexguitar commented on internal/handler/handler.go
> +			err := decoder.Decode(r.URL.Query(), &request.Body)
Не понял немного... А во что тогда декодировать тело?

2024-09-23 06:31 UTC, snaffi commented on internal/repo/user.go
> +		return nil, nil
а вернуть ошибку?

2024-09-23 06:31 UTC, snaffi approved these changes

2024-09-26 12:05 UTC, merged